[build]
release = true
dist = "dist"
public_url = "/brainwave-rs/"
filehash = false
# [[hooks]]
# stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "npx tailwindcss -i input.css -o style/output.css"]
